### PR TITLE
Fixes #133

### LINKED ISSUE #133: Why jest is declared as dependency? Why not it's in devDependency?
Hi! 
I've added `react-virtualized-tree` to my project and I'm seeing `jest` in dependency.
I believe that because of jest is required as a production dependency might be causing a problems in some cases. Is there a particular reason for it not to be in devDependencies?

### PR DESCRIPTION
**Pull request by atomicpages**

### CODE REVIEW

**Comment by atomicpages** [comment]
Maintaining a fork until then 😞  https://github.com/atomicpages/react-virtualized-tree

**Comment by diogofcunha** [comment]
Hi @atomicpages, thanks for this, sorry for the delay, I was a father recently and I'm only getting now the time to catchup 🙂

**Comment by atomicpages** [comment]
@diogofcunha no worries and congrats 🎉

**Pull request merged**
